jcsrc_proxy_homepage:
    path:     /
    methods: [GET]
    defaults: { _controller: jcsrc.proxy.defaut_controller:indexAction }

jcsrc_proxy_options:
    path:     /{client}/{service}
    methods: [OPTIONS]
    defaults: { _controller: jcsrc.proxy.defaut_controller:optionsAction }
    requirements:
        client: "[A-Za-z0-9_-]+"
        service: ".+"

jcsrc_proxy_service:
    path:     /{client}/{service}
    methods: [GET,POST,PATCH,HEAD,PUT]
    defaults: { _controller: jcsrc.proxy.defaut_controller:proxyAction, service: false }
    requirements:
        client: "[A-Za-z0-9_-]+"
        service: ".+"

jcsrc_proxy_service_schema:
    path:     /schema/{client}/{service}
    methods: [GET]
    defaults: { _controller: jcsrc.proxy.defaut_controller:schemaAction, service: false }
    requirements:
        client: "[A-Za-z0-9_-]+"
        service: ".+"
